### ISSUE TITLE
Joplin 2.8.8

### ISSUE THREAD

**Issue by didierm** [taw00/joplin-rpm#10]
Thank you for taking the time to distribute Joplin in .rpm format ; much appreciated.

Any chance Joplin v.2.8.8 (released June 7th) will be made available ?

**Comment by manojbaishya** [comment]
v2.8.8 is now available

https://copr.fedorainfracloud.org/coprs/taw/joplin/packages/

![image](https://user-images.githubusercontent.com/28330014/190230923-8fcdefaf-e3b4-42d8-824a-d1542434d54a.png)
