### ISSUE TITLE
Missing dependency for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Fietze** [taw00/joplin-rpm#11]
When trying to install Joplin Desktop following your instructions for openSUSE Tumbleweed I get this error message:

> Problem: 1: nothing provides 'libcanberra-gtk2' needed by the to be installed joplin-2.14.19-2.rp.suse.tw.taw.x86_64
>  Solution 1: do not install joplin-2.14.19-2.rp.suse.tw.taw.x86_64
>  Solution 2: break joplin-2.14.19-2.rp.suse.tw.taw.x86_64 by ignoring some of its dependencies

I have checked my installation and it shows 'libcanberra-gtk2-**module**' being installed.

**Comment by taw00** [comment]
This has been resolved via commit 02245af
