### ISSUE TITLE
Warning messages in Fedora 32 package

### ISSUE THREAD

**Issue by alusiani** [taw00/joplin-rpm#3]
Hi,

I am running joplin-1.0.227-1.fc32.taw.x86_64 in Fedora 32.

I note several warning messages in the debug log.  I get an error if I try to move a note to another notebook right-mouse-clicking on the note title in the note title panel.

The error may be, but also may be not, specific of the Fedora 32 package I am using.

I attach the debug log.

[joplin-debug-jul20.log](https://github.com/taw00/joplin-rpm/files/4917117/joplin-debug-jul20.log)

**Comment by taw00** [comment]
Upstream issue. In fact, it is this issue: https://github.com/laurent22/joplin/issues/3482
Dragging and dropping from one Notebook to another works fine. It is just that right-click bit that does not.

Reopen this or ping me if this is still an issue when the next release rolls out.
