### ISSUE TITLE
Error on Fedora 33

### ISSUE THREAD

**Issue by dziaineka** [taw00/joplin-rpm#5]
Hello! Got the error during `sudo dnf update`:

```
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:taw:joplin':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/taw/joplin/fedora-33-x86_64/repodata/repomd.xml (IP: 54.239.192.88)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:taw:joplin': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Thank you!

**Comment by taw00** [comment]
Yup. Doesn't exist yet. Joplin is not building on F33 just yet.

**Comment by taw00** [comment]
Got a working build. Test packages rolling within 30 to 45 minutes.
I *do not* have a running F33 desktop to test it through. Marking the package testing.

**Comment by taw00** [comment]
Fedora 33 build posted. Please report any problems. Thank you. -t
