### ISSUE TITLE
Automated package builds

### ISSUE THREAD

**Issue by mcejp** [taw00/joplin-rpm#7]
Hi, I am a big fan of Joplin and of this project.
Do I understand correctly that at the moment, you build the RPMs by hand whenever there is a new Joplin release? If so, do you think there would be value in trying to automate this process, e.g. through GitHub Actions?

Thanks for your work,
Martin

**Comment by taw00** [comment]
I build the RPMs via COPR. Is there a way to automate that? I don't know to be honest. Worth looking into.
