### ISSUE TITLE
Could you please build for Fedora 35 too

### ISSUE THREAD

**Issue by eclipseo** [taw00/joplin-rpm#9]
This is one of the last package I need to update to F35 beta. The other being Element, which would be nice to make available for F35 too.

Thanks.

**Comment by r3pek** [comment]
Just "hijacking" this thread to request F36. Please? ;)

**Comment by didierm** [comment]
Fixed by https://github.com/taw00/joplin-rpm/issues/10

**Comment by taw00** [comment]
This has been addressed a long time ago. Closing.
